name: rionidenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - beautifulsoup4
  - nibabel
  - fortranformat
  - ezodf
  - loguru
  - pyqt
  - pyqtgraph
  - toml
  - watchdog
  - pip
  - pip:
      - git+https://github.com/xaratustrah/iqtools.git#egg=iqtools
      - nptdms
      - pytdms
      - uproot3
      - uproot3_methods
      - git+https://github.com/xaratustrah/barion.git#egg=barion
      - git+https://github.com/gwgwhc/lisereader.git#egg=lisereader
