site_name: RionID Documentation
site_description: "Ring-stored ion IDdentification: Library to perform particle identification of a Schottky spectrum."
site_url: "https://DFreireF.github.io/rionid"
repo_url: "https://github.com/DFreireF/rionid"
edit_uri: "blob/main/docs/"
repo_name: "DFreireF/rionid"
site_dir: "site"
watch: [README.md]

theme:
  name: material
  logo: img/rionid2.png
  highlightjs: true
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist

plugins:
  - search
  - mkdocstrings

nav:
  - Main page: index.md
  - Prerionid:
    - __main__: prerionid/__main__.md
    - datacrunch: prerionid/datacrunch.md
    - e0018: prerionid/e0018.md
    - psdata: prerionid/psdata.md
    - watcher: prerionid/watcher.md
  - RionID:
    - __main__: rionid/__main__.md
    - creategui: rionid/creategui.md
    - importdata: rionid/importdata.md
    - inputtools: rionid/inputtools.md
    - pypeaks: rionid/pypeaks.md
    - pyqtgraphgui: rionid/pyqtgraphgui.md
  - RionID GUI:
    - __main__: rionidgui/__main__.md
    - gui: rionidgui/gui.md
    - gui_controller: rionidgui/gui_controller.md
    - parameter_gui: rionidgui/parameter_gui.md

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/DFreireF
copyright: |
  &copy; 2023 <a href="https://github.com/DFreireF"  target="_blank" rel="noopener">David Freire Fernández</a>
